apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: green
  namespace: dev
spec:
  selector:
    matchLabels:
      app: green
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: green
        tier: frontend
    spec:
      containers:
      - name: green
        image: ${REPOSITORY_TAG}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: green
  namespace: dev
spec:
  selector:
    app: green
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
